apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-app.fullname" . }}
  labels:
    {{- include "test-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: flask-port
  selector:
    app.kubernetes.io/name: {{ include "test-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
